Factor out REST call

diff --git a/weaver/weave b/weaver/weave
--- a/weaver/weave
+++ b/weaver/weave
@@ -224,6 +224,27 @@ detach() {
     ip link del $LOCAL_IFNAME type veth
 }
 
+# Call url $3 on program $2 with http verb $1
+rest_call() {
+    http_verb="$1"
+    if ! DOCKERIP=$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' $2 2>/dev/null) ; then
+        echo "$2 is not running." >&2
+        exit 1
+    fi
+    if [ -z "$DOCKERIP" ] ; then
+        echo "$2 is not running." >&2
+        exit 1
+    fi
+    url="$3"
+    shift 3
+    if command_exists curl ; then
+        curl -s -X $http_verb "$@" $DOCKERIP:$url
+    else
+        echo "Cannot find curl, which is required for this operation." >&2
+        exit 1
+    fi
+}
+
 case "$COMMAND" in
     launch)
         [ $# -gt 0 ] || usage
@@ -264,22 +285,7 @@ case "$COMMAND" in
         echo $CONTAINER
         ;;
     status)
-        if ! DOCKERIP=$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' weave 2>/dev/null) ; then
-            echo "Weave is not running." >&2
-            exit 1
-        fi
-        if [ -z "$DOCKERIP" ] ; then
-            echo "Weave is not running." >&2
-            exit 1
-        fi
-        if command_exists wget ; then
-            wget -O - -q $DOCKERIP:6784/status
-        elif command_exists curl ; then
-            curl $DOCKERIP:6784/status
-        else
-            echo "Cannot find wget or curl. Install one of them for 'weave status' to function." >&2
-            exit 1
-        fi
+        rest_call GET weave 6784/status
         ;;
     version)
         # Try the running container first; if no luck try the image
